### PR TITLE
Change to DateTimeOffset for OData 4

### PR DESCRIPTION
**Pull request by frabcus**
See discussion here: http://scn.sap.com/thread/3441583

See examples here: http://msdn.microsoft.com/en-us/library/ff478141.aspx

This hopefully will make it work with Tableau 8.2

### CODE REVIEW

**Comment by frabcus** [comment]
This should fix #1 

@pwaller can you review, and show me how to deploy :)

**Comment by pwaller** [comment]
:+1:.

Deploy is by following instructions in the usual place. Should be of the form 'run this sls'. Let me know if you can't find them.

**Comment by pwaller** [comment]
@frabcus @IanHopkinson do we need to test this doesn't break old/new Tableau?

**Comment by frabcus** [comment]
Yeah, so this needs testing and deploying.

I think we should buy/get a second copy of Tableau - might be able to
do this test with a free trial.

Francis

**Pull request merged**
